repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace  # убирает лишние пробелы
    -   id: check-added-large-files  # проверяет тяжелые файлы на изменения
    -   id: check-yaml  # проверяет синтаксис .yaml файлов
    -   id: check-json  # проверяет синтаксис .json файлов
        exclude: launch.json
    -   id: check-case-conflict  # проверяет файлы, которые могут конфликтовать в файловых системах без учета регистра.
    -   id: check-merge-conflict  # проверяет файлы, содержащие конфликтные строки слияния.
    -   id: end-of-file-fixer  # добавляет пустую строку в конце файла

# Отсортировывает импорты в проекте
-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
      - id: isort
        exclude: __init__.py
        args: [ --profile, black, --filter-files ]


# Форматирует код под PEP8
-   repo: https://github.com/pre-commit/mirrors-autopep8
    rev: v2.0.4
    hooks:
    -   id: autopep8
        args: [--max-line-length=120, --in-place]

# Сканер стилистических ошибок, нарушающие договоренности PEP8
-   repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
    -   id: flake8
        exclude: "__init__.py"
        args: ["--ignore=E501,F821", "--max-line-length=120"]

# The Uncompromising Code Formatter
-   repo: https://github.com/psf/black
    rev: 23.10.1
    hooks:
    - id: black
      language_version: python3.10

## An extremely fast Python linter and code formatter, written in Rust
#- repo: https://github.com/astral-sh/ruff-pre-commit
#  # Ruff version.
#  rev: v0.1.4
#  hooks:
#    - id: ruff-format
#      args: [--check]
