version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MONGO_DB=mongodb://mongodb/
      - AUTH_CHECK_TOKEN=http://172.23.0.5:8000/user/verify_token/
      - AUTH_CREATE_TPI=http://172.23.0.5:8000/api/v1/tpi/
    container_name: app_analytics
    ports:
      - '8080:8080'
    entrypoint: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload --log-level debug"
    networks:
      - analytics_network
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    container_name: "mongodb"
    image: mongo:7
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - analytics_network

networks:
  analytics_network:
    name: smart_drive
    driver: bridge
    external: true
