version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: app_analytics
#    env_file:
#      - .env
    ports:
      - '8000:8000'
    entrypoint: sh -c "alembic upgrade head && uvicorn app.main:app --host 0.0.0.0 --port 8000"

  mongo_db:
    container_name: mongo_db_analytics
    image: mongo:7
    ports:
      - "25017:25017"
