version: '3.8'
services:
  app:
    container_name: app-analytics
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    environment:
      - MONGO_DB=${MONGO_DB}
      - AUTH_CHECK_TOKEN_URL=${AUTH_CHECK_TOKEN_URL}
      - AUTH_CREATE_TPI_URL=${AUTH_CREATE_TPI_URL}

    ports:
      - '8080:8080'
    entrypoint: sh -c "uvicorn src.main:app --host 0.0.0.0 --port 8080 --reload --log-level debug"
    networks:
      - common-network
    depends_on:
      - mongodb
    links:
      - mongodb

  mongodb:
    container_name: "mongodb"
    image: mongo:7
    env_file:
      - .env
    ports:
      - ${MONGO_PORT}:${MONGO_PORT}
    networks:
      - common-network

#networks:
#  analytics_network:
#    name: smart_drive
#    driver: bridge
#    external: true

networks:
  common-network:
    driver: bridge
    external: true
